version: '3.9'

services:
  postgres:
    image: postgres:15.8
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: sionic
      POSTGRES_PASSWORD: sionic123
      POSTGRES_DB: sionic_ai
      TZ: Asia/Seoul
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U sionic -d sionic_ai']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
